### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by ziggi** [Southclaw/pawn-sublime-language#33]
Please add a LICENSE file: https://help.github.com/articles/open-source-licensing/
I can not make a pull request to linguist for add Pawn into GitHub without this.

**Comment by Patrik356b** [comment]
Perhaps add the boost license? - It's short and simplistic.
Example: https://github.com/Patrik356b/CustomVehicleDamage/blob/master/LICENSE.md

**Comment by ziggi** [comment]
Thank you, Southclaw (cd22881d2574aa3fa7d88ff7258e0c69a3d3ae28).
