### ISSUE TITLE
Not write error 

### ISSUE THREAD

**Issue by ITCMatus** [Southclaw/pawn-sublime-language#34]
Hi.
I use Sublime Text 3 and don't write error list. 
I'm try reinstall 3x sublime text but it did not work. 
Please how to fix it? 

me build code: 

{
	"cmd": ["pawncc.exe", "$file", "-o$file_path\\\\$file_base_name", "-;+", "-(+", "-d3", "-Z+"],
	"file_regex": "(.*?)[(]([0-9]*)[)]",
	"selector": "source.pwn",
	"working_dir": "C:\\Users\\Matúš\\Documents\\SAMP\\KOMPILATOR"
}

![bez nazvu](https://cloud.githubusercontent.com/assets/12234883/10117131/fcf8622e-644c-11e5-9c00-76cff267f0a0.png)

**Comment by Southclaw** [comment]
This probably isn't an issue with this particular plugin, though I should imagine it's the "-Z+" flag you have there (which, as far as I can tell, isn't even a valid argument).

**Comment by PatchwerkQWER** [comment]
O.o http://misiur.github.io/2015/03/23/y_groups-making-factions-in-sa-mp-has-never-been-easier/ Here Misiur talk about "-Z+" tag
I have "-Z+" tag too and everything works ^.^

**Comment by PatchwerkQWER** [comment]
@Southclaw Have you another tip? It's really annoying. Here's someone else with same problem. http://forum.sa-mp.com/showthread.php?t=590370

Cheers

**Comment by Southclaw** [comment]
I can't get this to reproduce on my end, Sublime Text 3 latest build with the normal compiler. I've never seen this happen before even while developing. If you're using Zeex's compiler can you confirm it's only occurring with that compiler?

**Comment by Hirsw0w** [comment]
I had the same problem and I fixed by the working dir only english my pawn dir was in hebrew
and that cause the problem maybe the windows user cause the problem

**Comment by Patrik356b** [comment]
There are random issues when using non-english characters in the path of
some compilers

On Sun, Oct 4, 2015 at 11:32 AM, Hirsw0w <notifications@github.com> wrote:

> I had the same problem and I fixed by the working dir only english my pawn
> dir was in hebrew
> and that cause the problem maybe the windows user cause the problem
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Southclaw/pawn-sublime-language/issues/34#issuecomment-145330059>
> .
>



-- 
Best regards; Hexile
