### ISSUE TITLE
Charset?

### ISSUE THREAD

**Issue by PatchwerkQWER** [Southclaw/pawn-sublime-language#35]
Hi

Which charset I should use for czech/slovak characters? Because when I have `UTF-8` it display weird chars.

Screen code:
![Screenshott](https://ctrlv.cz/shots/2015/10/13/N4QT.png)
Screen ingame:
![Screenshott](https://ctrlv.cz/shots/2015/10/13/fTmm.png)

But when I use `Central European (Windows 1250)` it works ingame but when I try save special characters to file (like chatlog, etc...) it again save weird chars.

Screen from chatlog when I compile gamemode in `Central European (Windows 1250)` charset:
![Screenshott](https://ctrlv.cz/shots/2015/10/13/zshA.png)

Thanks for any help
Cheers

**Comment by Southclaw** [comment]
I'm not sure if this is a compiler issue or a sublime text issue. There is some information on the forums about character sets and compiling for different languages. I can't recall anything specific at the moment though, sorry. I don't think this is an issue with the plugin either unless it requires parameters to be passed to the compiler explicitly.

**Comment by Southclaw** [comment]
Did you solve this issue? I'll close it here since I assume it's related to the compiler or sublime settings rather than this particular package.

**Comment by PatchwerkQWER** [comment]
Nope. I didn't solve this. I end with samp.
