### ISSUE TITLE
Open SAMP wiki

### ISSUE THREAD

**Issue by doreto** [Southclaw/pawn-sublime-language#44]
Is possible to be made when you mark up something and press key to open samp wiki for that specific selection. Example: `PutPlayerInVehicle` then i press `Ctrl+F1` and opens http://wiki.sa-mp.com/wiki/PutPlayerInVehicle

**Comment by Southclaw** [comment]
I believe that is possible through a Python script bound to a key, I'll look into it.

**Comment by doreto** [comment]
Thanks and i hope it can be done.

**Comment by Southclaw** [comment]
Something like this should work (quick code notes for when I get home later)

```
import sublime, sublime_plugin
import webbrowser

class OpenWikiOnString(sublime_plugin.TextCommand):

	def run(self, edit):
		query = self.view.sel()[0]
		webbrowser.open_new("http://wiki.sa-mp.com/wiki/" + query)
```
Then just bind this class to a shortcut in the keyboard config.
