### ISSUE TITLE
Wrong highlighting for symbolic option in switch/case construction

### ISSUE THREAD

**Issue by ziggi** [Southclaw/pawn-sublime-language#48]
The error in [this](https://github.com/Southclaw/pawn-sublime-language/blob/master/Pawn.tmLanguage#L952) regular expression. He should check for **case** at line, but I don't know how to make that.

But it is not major bug, because the use braces in each code construction is a basic rule of writing code.

```Pawn
// this code highlighting is incorrect, and this code is crap
case QWE: return 1;
// this code highlighting is correct, and this code is crap
case QWE:
     return 1;
// this code highlighting is correct, and this code is cool
case QWE: {
    return 1;
}
// this code highlighting is correct, and this code is cool
case QWE:
{
    return 1;
}
```

# Screenshot
![2x4h2wv](https://cloud.githubusercontent.com/assets/1020099/14740070/c635a638-0894-11e6-847d-832f01486386.png)

**Comment by Southclaw** [comment]
It's up to the writer or company they work for to decide what style the code should be in, not the highlighter, I personally do use no-brace blocks for single function calls (the second type).

I did originally attempt to apply a highlight to the entire "case" section with ```case\s*(([a-zA-Z_@0-9])*([\s,\.]))*(([a-zA-Z_@0-9])*\:)``` but it was ignored in favour of tag highlighting. So I decided to ignore cases from tag matching with ```^(?!case.*)\s*\b([A-Za-z_]\w*)\:\s*\b``` and it seems to work!

![https://dl.dropboxusercontent.com/u/45512231/ShareX/sublime_text_2016-04-22_16-09-55.png](https://dl.dropboxusercontent.com/u/45512231/ShareX/sublime_text_2016-04-22_16-09-55.png)

**Comment by ziggi** [comment]
Nice, it is works. Good job!

**Comment by Kar2k** [comment]
Amazing. There's only one moire case issue i see. 

Number ranges aren't coloured to purple.

[http://prntscr.com/avi6s8](url)

**Comment by Southclaw** [comment]
That should be a pretty easy one to fix if I apply it to all numeric expressions.

**Comment by Southclaw** [comment]
Attempted a fix for .. range specifier in the latest commit.
