### ISSUE TITLE
wrong highlighting

### ISSUE THREAD

**Issue by acuworld** [Southclaw/pawn-sublime-language#49]
![1](https://cloud.githubusercontent.com/assets/2685630/14761860/0b352098-09a7-11e6-9758-3a772a2c3580.png)

what's wrong...

**Comment by Southclaw** [comment]
That's just the old syntax on the current version ["You may notice some illegal markers on #elseifs and other preprocessor definitions, ignore these for now."](https://github.com/Southclaw/pawn-sublime-language/releases/tag/v1.6.3) new release coming shortly.
