### ISSUE TITLE
Add suport for macros

### ISSUE THREAD

**Issue by Dayvison** [Southclaw/pawn-sublime-language#57]
@e103b3cb660e4732f2ef3ce2b8d9b8530a5bbcfe

If you can help with improve this, is a good enchant

Sorry my bad, bad english

**Comment by Southclaw** [comment]
I'll check it out this morning, thanks!

**Comment by Southclaw** [comment]
This code seems to work fine, feel free to submit a pull request!

**Comment by Dayvison** [comment]
#58
